Add option to skip attendances
camptocamp/gtimelog2odoo pull request #11
Opened 2020-04-28 05:44 UTC by simahawk

2020-04-28 06:28 UTC, Tonow-c2c approved these changes

2020-04-28 09:07 UTC, i-vyshnevska requested changes
you also need to disable login to odoo if option is given

2020-04-28 14:00 UTC, simahawk commented
> you also need to disable login to odoo if option is given

you are right. I'll have a look tomorrow

2020-04-29 06:04 UTC, simahawk commented
@i-vyshnevska should be better now:

* no login
* no report
* support rc config (no need to pass the flag everytime)

2020-04-29 06:24 UTC, asaunier commented on README.md
> +If you want to skip attendances youn can use `--no-attendance` or set `no_attendance = 1` in `gtimelogrc`.
```suggestion
If you want to skip attendances you can use `--no-attendance` or set `no_attendance = 1` in `gtimelogrc`.
```

2020-04-29 06:31 UTC, i-vyshnevska approved these changes
functional test +

2020-04-30 05:46 UTC, merged