Update base demo file
camptocamp/gtimelog2odoo pull request #15
Opened 2023-03-27 07:58 UTC by leemannd

2023-03-27 08:10 UTC, SilvioC2C approved these changes

2023-03-27 08:40 UTC, florentx reviewed
I don't understand the proposed change. There are already `odoo_port` and `odoo_protocol` ?

It looks like duplication, or I missed something?

2023-03-27 08:44 UTC, florentx requested changes
See comment.

2023-03-28 10:08 UTC, florentx commented
PR #16 is correct. I close this one

2023-03-28 10:08 UTC, closed without merging