Add `category: task description | comment` format
camptocamp/gtimelog2odoo pull request #5
Opened 2019-05-06 13:07 UTC by yvaucher

To keep a better reporting on gtimelog, one might want to
still use the category to group some tasks together.

Also add the possibility to insert comment that won't be pushed to jira.

2019-05-06 13:11 UTC, simahawk requested changes
can you explain why we need these changes?

2019-05-09 07:20 UTC, TDu commented
I like the private comment addition, I actually used it before, I find it really useful when working on large task. When trying to implement one chunk of work  I keep the public description nice and correct and the same for a few hours logged (with interruption) private description would contain more information on the speed bumps I encounter and yes why not also some swear words.
Not that I really reread those comments later on. But they would be my go to information if later on, I need to recall what happen with all that time I burnt ;)

2019-05-09 07:26 UTC, TDu approved these changes
As I said earlier I like the private comment addition. I probably won't use the category one but as far as I can see it is an opt-in option that has no impact if not activated.

2019-05-09 11:34 UTC, guewen commented
My problem with the category is how do you know how much time you already spent on a specific card on a daily/weekly basis? This is the information you should track and keep under the eyes, *always*, not the global time spent on a project (you need it occasionally and find it in Odoo).

2019-05-10 05:53 UTC, simahawk commented
> private description would contain more information on the speed bumps I encounter and yes why not also some swear words.
> Not that I really reread those comments later on. 

To me private description is useless, especially if you don't read it, as you said :)

"speed bumps", blocks, etc **they should be mentioned in the real description OR reported on the card** straight. If they stay in a private-no-body-will-read-it-anymore-place, again: is useless.

Regarding the grouping by project: this is not what gtimelog is meant to do.
Its purpose is to track time on an activity and not on a larger scope.
And all in all this is what we need: track time on the activities.
For more generic activities we already have the aliases.

Both of these features were actually removed because of the above reasons.

Regarding "how do I see how much time I spent overall on a project" -> it's easy: push TS every day and check on JIRA ;)
There you get a much better vision on the time you spent per day, per week, per month, per whatever.

Now, my request of explanation was about "do we really need this to make our daily work more efficient?". TBH it seems not, but since it's already done and is not affecting prior behavior, we can add it. 

My concern is mostly about not spending too much time on adapting this tool for each of us.
We've already spent a lot of time to get there (no matter who did it), so if we really need (and have) time to spend on this it must be for an important issue that affects every one.

For instance: it sets the remaining estimate to 0h. But even this might not be a big issue to rush for: you can still see the time spent and compare what's left yourself.

To wrap it up: pls, let's decide improvements/fixes together and file a card for them :pray:

2019-05-10 06:02 UTC, simahawk approved these changes

2019-05-10 06:02 UTC, merged